name: Trigger auto deployment for aca-petcliaca-admin-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'docker/petclinic-admin-server/**'
    - '.github/workflows/aca-petcliaca-admin-server-AutoDeployTrigger-ee2187cd-5df4-47d1-8c97-01e645b2aae1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrpetcliaca.azurecr.io
          username: ${{ secrets.ACAPETCLIACAADMINSERVER_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAPETCLIACAADMINSERVER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrpetcliaca.azurecr.io/petclinic/petclinic-admin-server:${{ github.sha }}
          file: docker/petclinic-admin-server/Dockerfile
          context: docker/petclinic-admin-server/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAPETCLIACAADMINSERVER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-petcliaca-admin-server -g rg-iac-aca-petclinic-mic-srv --server acrpetcliaca.azurecr.io --username  ${{ secrets.ACAPETCLIACAADMINSERVER_REGISTRY_USERNAME }} --password ${{ secrets.ACAPETCLIACAADMINSERVER_REGISTRY_PASSWORD }}
            az containerapp update -n aca-petcliaca-admin-server -g rg-iac-aca-petclinic-mic-srv --image acrpetcliaca.azurecr.io/petclinic/petclinic-admin-server:${{ github.sha }}
