# https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
# Warning: The `set-output` command is deprecated and will be disabled soon. 
# Please upgrade to using Environment Files. 
name: Caller Test Workflow

env:
  APP_NAME: petcliaca

on:
  workflow_dispatch:

jobs:

  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  # invalid value workflow reference: references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
  call-workflow:
    name: Trigger other Workflow
    uses: ./.github/workflows/called-test.yml # .github/workflows/maven-build.yml@main ==> references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
    secrets: inherit # pass all secrets
      # envPAT: ${{ secrets.envPAT }} # pass just this secret

  post-call-workflow:
    needs: call-workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read    
    steps:
    - name: verify
      run: |
          echo "Checking tagid output ... : " ${{ needs.call-workflow.outputs.tagid }}
          tagid=${{ needs.call-workflow.outputs.tagid }}
          echo "Image Build tag ID:"$tagid
          echo "Image Build tag ID from {{ env.tag_id }}: "${{ env.tag_id }}
          echo "Image Build tag ID from GITHUB_OUTPUT: "$GITHUB_OUTPUT          
      shell: bash