name: Caller Test Workflow

env:
  APP_NAME: petcliaca

on:
  workflow_dispatch:

jobs:

  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  # invalid value workflow reference: references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
  call-workflow:
    name: Trigger Maven
    uses: ./.github/workflows/called-test.yml # .github/workflows/maven-build.yml@main ==> references to workflows must be prefixed with format 'owner/repository/' or './' for local workflows
    secrets: inherit # pass all secrets
      # envPAT: ${{ secrets.envPAT }} # pass just this secret

  deploy-apps:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
          echo "Checking tag_id output ... : " ${{ needs.call-workflow.outputs.tag_id }}
          tag_id=${{ needs.call-workflow.outputs.tag_id }}
          echo "Image Build tag ID:"$tag_id
      shell: bash