name: Called Test Workflow

env:
  APP_NAME: petcliaca

on:
  workflow_dispatch:

  workflow_call:
    outputs:
      tag_id:
        description: "The Maven Build job output"
        value: ${{ jobs.called-workflow.outputs.tag_id }}
jobs:
  called-workflow:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.test.outputs.tag_id }}
    steps:
    - name: test
      run: |
          # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
          # GITHUB_SHA: The commit SHA that triggered the workflow
          # GITHUB_RUN_ID: A unique number for each workflow run within a repository. This number does not change if you re-run the workflow run.
          tag_id=$GITHUB_SHA
          echo "GITHUB_RUN_ID="$GITHUB_RUN_ID
          echo "GITHUB_SHA="$GITHUB_SHA
          echo "run_id="${{ github.run_id }}
          echo "github.sha="${{ github.sha }}
          
          echo "tag_id="$tag_id
          echo $GITHUB_SHA | cut -c1-8 >> $GITHUB_ENV
          echo "SHORT_SHA cut="${{ env.SHORT_SHA }}

          # echo $GITHUB_SHA::7 >> $GITHUB_ENV # https://tldp.org/LDP/abs/html/parameter-substitution.html
          # echo "SHORT_SHA param substitution="${{ env.SHORT_SHA }}

          tag_id=${{ env.SHORT_SHA }}
          echo "::set-output name=tag_id::$tag_id"  # mismatch with ACR {{.Run.ID}}. {{.Run.ID}} would be different for each az acr build 
          
      shell: bash

  check:
    runs-on: ubuntu-latest
    needs: called-workflow
    steps:
    - name: trace
      run: |
          tag_id=${{ needs.called-workflow.outputs.tag_id }}
          echo "Image Build tag ID:"$tag_id
      shell: bash