name: Called Test Workflow

env:
  APP_NAME: petcliaca

on:
  workflow_dispatch:

  workflow_call:
    outputs:
      tag_id:
        description: "The Maven Build job output"
        value: ${{ jobs.maven-build.outputs.tag_id }}
jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:

    - name: test
      run: |
          # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
          # GITHUB_SHA: The commit SHA that triggered the workflow
          # GITHUB_RUN_ID: A unique number for each workflow run within a repository. This number does not change if you re-run the workflow run.
          echo "::set-output name=tag_id::$GITHUB_SHA"  #m mismatch with ACR {{.Run.ID}}. {{.Run.ID}} would be different for each az acr build 
          tag_id=$GITHUB_SHA
          echo "GITHUB_RUN_ID="$GITHUB_RUN_ID
          echo "GITHUB_SHA="$GITHUB_SHA
          echo "GITHUB_RUN_ID="${{ github.run.id }}
          echo "github.sha="${{ github.sha }}
          
          echo "tag_id="$tag_id
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "SHORT_SHA cut="$SHORT_SHA

          echo "SHORT_SHA=`echo ${GITHUB_SHA::7}`" >> $GITHUB_ENV
          echo "SHORT_SHA param substitution="$SHORT_SHA # https://tldp.org/LDP/abs/html/parameter-substitution.html
      shell: bash

    # security hardening for self-hosted agents: https://github.com/marketplace/actions/azure-login
    # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners
    # if the runner is self-hosted which is not github provided it is recommended to manually logout at the end of the workflow as shown below.
    - name: Azure Logout security hardening
      run: |
          az logout
          az cache purge
          az account clear
      shell: bash
  
    outputs:
      tag_id: ${{ steps.test.outputs.tag_id }}