# This workflow will delete all the ACA Apps
name: Delete Apps

env:
  LOCATION: westeurope
  RG_APP: rg-iac-aca-petclinic-mic-srv # RG where to delete the ACA Apps

  APP_NAME: petcliaca
  
  ADMIN_SERVER: aca-petcliaca-admin-server # 'aca-${appName}-admin-server' ==> aca-petcliaca-admin-server
  CONFIG_SERVER: aca-petcliaca-config-server
  DISCOVERY_SERVER: aca-petcliaca-discovery-server

  API_GATEWAY: aca-petcliaca-api-gateway
  CUSTOMERS_SERVICE: aca-petcliaca-customers-service
  VETS_SERVICE: aca-petcliaca-vets-service
  VISITS_SERVICE: aca-petcliaca-visits-service

  # https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md#consume-secrets-in-your-workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-secrets

  # ==== Secrets ====
  credentials: ${{ secrets.AZURE_CREDENTIALS }}

  # ==== Versions ====
  AZ_CLI_VERSION: 2.40.0

on:
  workflow_dispatch:

jobs:
  delete-rg:
    runs-on: ubuntu-latest

    steps:

    - name: Azure Login
      uses: azure/login@v1.4.6 # https://github.com/marketplace/actions/azure-login
      with:
        creds: ${{ env.credentials }}

    - name: Delete Apps
      uses: azure/CLI@v1.0.6 # https://github.com/marketplace/actions/azure-cli-action
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          
          az containerapp list -g ${{ env.RG_APP }}

          for app in $(az containerapp list -g  ${{ env.RG_APP }} | jq -r '.[].name')
          do
            echo "About to delete App " $app
            # az containerapp delete --name $app -g ${{ env.RG_APP }} --yes
          done

          az containerapp delete --name ${{ env.ADMIN_SERVER }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.VISITS_SERVICE }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.VETS_SERVICE }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.CUSTOMERS_SERVICE }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.API_GATEWAY }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.CONFIG_SERVER }} -g ${{ env.RG_APP }} --yes
          az containerapp delete --name ${{ env.DISCOVERY_SERVER }} -g ${{ env.RG_APP }} --yes

    # security hardening for self-hosted agents: https://github.com/marketplace/actions/azure-login
    # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners
    # if the runner is self-hosted which is not github provided it is recommended to manually logout at the end of the workflow as shown below.
    - name: Azure Logout security hardening
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VERSION }}
        inlineScript: |
          az logout
          az cache purge
          az account clear